[toolchain]
anchor_version = "1.0.0"
solana_version = "3.1.13"

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
shain = "2T1Qs7f2hiy1sUQBWC7226xhXvCees97UfeqReRrnE66"

[programs.devnet]
shain = "2T1Qs7f2hiy1sUQBWC7226xhXvCees97UfeqReRrnE66"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
